# Generated by Django 5.1.7 on 2026-01-05 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Class Name")),
            ],
            options={
                "verbose_name": "Class",
                "verbose_name_plural": "Classes",
                "indexes": [
                    models.Index(fields=["name"], name="form_class_name_029e38_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "zeng",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "Period 1"),
                            (2, "Period 2"),
                            (3, "Period 3"),
                            (4, "Period 4"),
                            (5, "All Periods"),
                        ],
                        verbose_name="Period",
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(blank=True, null=True, verbose_name="Start Time"),
                ),
                (
                    "end_time",
                    models.TimeField(blank=True, null=True, verbose_name="End Time"),
                ),
            ],
            options={
                "verbose_name": "Schedule",
                "verbose_name_plural": "Schedules",
                "indexes": [
                    models.Index(fields=["zeng"], name="form_schedu_zeng_b6b0fb_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="ClassSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("Sat", "Saturday"),
                            ("Sun", "Sunday"),
                            ("Mon", "Monday"),
                            ("Tue", "Tuesday"),
                            ("Wed", "Wednesday"),
                        ],
                        max_length=3,
                        verbose_name="Day",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        default="", max_length=100, verbose_name="Subject"
                    ),
                ),
                (
                    "unit",
                    models.CharField(default="", max_length=10, verbose_name="Unit"),
                ),
                (
                    "is_split",
                    models.BooleanField(default=False, verbose_name="Split Period"),
                ),
                (
                    "split_part",
                    models.PositiveIntegerField(default=0, verbose_name="Split Part"),
                ),
                (
                    "class_obj",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="form.class",
                        verbose_name="Class",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_schedules",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Teacher",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_schedules",
                        to="form.schedule",
                        verbose_name="Schedule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Class Schedule",
                "verbose_name_plural": "Class Schedules",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_number", models.PositiveIntegerField(verbose_name="Row Number")),
                (
                    "first_name",
                    models.CharField(max_length=50, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=50, verbose_name="Last Name"),
                ),
                (
                    "father_name",
                    models.CharField(max_length=50, verbose_name="Father's Name"),
                ),
                (
                    "class_obj",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="form.class",
                        verbose_name="Class",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student",
                "verbose_name_plural": "Students",
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("P", "Present"), ("A", "Absent"), ("L", "Late")],
                        default="P",
                        max_length=1,
                        verbose_name="Status",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True, verbose_name="Date")),
                (
                    "class_schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="form.classschedule",
                        verbose_name="Class Schedule",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="form.student",
                        verbose_name="Student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance",
                "verbose_name_plural": "Attendances",
            },
        ),
        migrations.AddIndex(
            model_name="classschedule",
            index=models.Index(
                fields=["class_obj", "schedule", "day"],
                name="form_classs_class_o_8aa1e2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["first_name", "last_name"],
                name="form_studen_first_n_0d3183_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["student", "date"], name="form_attend_student_6d0a4d_idx"
            ),
        ),
    ]
