# Generated by Django 5.2.6 on 2025-10-16 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام کلاس")),
            ],
            options={
                "verbose_name": "کلاس",
                "verbose_name_plural": "کلاس\u200cها",
            },
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "zeng",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "زنگ ۱"),
                            (2, "زنگ ۲"),
                            (3, "زنگ ۳"),
                            (4, "زنگ ۴"),
                            (5, "تمام زنگ\u200cها"),
                        ],
                        verbose_name="زنگ",
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(blank=True, null=True, verbose_name="زمان شروع"),
                ),
                (
                    "end_time",
                    models.TimeField(blank=True, null=True, verbose_name="زمان پایان"),
                ),
            ],
            options={
                "verbose_name": "برنامه زنگ",
                "verbose_name_plural": "برنامه زنگ\u200cها",
            },
        ),
        migrations.CreateModel(
            name="ClassSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("Sat", "شنبه"),
                            ("Sun", "یک\u200cشنبه"),
                            ("Mon", "دوشنبه"),
                            ("Tue", "سه\u200cشنبه"),
                            ("Wed", "چهارشنبه"),
                        ],
                        max_length=3,
                        verbose_name="روز هفته",
                    ),
                ),
                (
                    "subject",
                    models.CharField(default="", max_length=100, verbose_name="درس"),
                ),
                (
                    "unit",
                    models.CharField(default="", max_length=10, verbose_name="واحد"),
                ),
                (
                    "is_split",
                    models.BooleanField(default=False, verbose_name="تقسیم زنگ"),
                ),
                (
                    "split_part",
                    models.PositiveIntegerField(default=0, verbose_name="بخش تقسیم"),
                ),
                (
                    "class_obj",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="form.class",
                        verbose_name="کلاس",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_schedules",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="معلم",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_schedules",
                        to="form.schedule",
                        verbose_name="زنگ",
                    ),
                ),
            ],
            options={
                "verbose_name": "برنامه کلاس",
                "verbose_name_plural": "برنامه کلاس\u200cها",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_number", models.PositiveIntegerField(verbose_name="شماره ردیف")),
                ("first_name", models.CharField(max_length=50, verbose_name="نام")),
                (
                    "last_name",
                    models.CharField(max_length=50, verbose_name="نام خانوادگی"),
                ),
                (
                    "father_name",
                    models.CharField(max_length=50, verbose_name="نام پدر"),
                ),
                (
                    "class_obj",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="form.class",
                        verbose_name="کلاس",
                    ),
                ),
            ],
            options={
                "verbose_name": "دانش\u200cآموز",
                "verbose_name_plural": "دانش\u200cآموزان",
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("P", "حضور"), ("A", "غایب"), ("L", "تاخیر")],
                        default="P",
                        max_length=1,
                        verbose_name="وضعیت",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True, verbose_name="تاریخ")),
                (
                    "class_schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="form.classschedule",
                        verbose_name="برنامه کلاس",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="form.student",
                        verbose_name="دانش\u200cآموز",
                    ),
                ),
            ],
            options={
                "verbose_name": "حضور و غیاب",
                "verbose_name_plural": "حضور و غیاب\u200cها",
            },
        ),
    ]
