# Generated by Django 5.2.6 on 2025-10-16 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendance",
            options={
                "verbose_name": "Attendance",
                "verbose_name_plural": "Attendances",
            },
        ),
        migrations.AlterModelOptions(
            name="class",
            options={"verbose_name": "Class", "verbose_name_plural": "Classes"},
        ),
        migrations.AlterModelOptions(
            name="classschedule",
            options={
                "verbose_name": "Class Schedule",
                "verbose_name_plural": "Class Schedules",
            },
        ),
        migrations.AlterModelOptions(
            name="schedule",
            options={"verbose_name": "Schedule", "verbose_name_plural": "Schedules"},
        ),
        migrations.AlterModelOptions(
            name="student",
            options={"verbose_name": "Student", "verbose_name_plural": "Students"},
        ),
        migrations.AlterField(
            model_name="attendance",
            name="class_schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances",
                to="form.classschedule",
                verbose_name="Class Schedule",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="date",
            field=models.DateField(auto_now_add=True, verbose_name="Date"),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                choices=[("P", "Present"), ("A", "Absent"), ("L", "Late")],
                default="P",
                max_length=1,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances",
                to="form.student",
                verbose_name="Student",
            ),
        ),
        migrations.AlterField(
            model_name="class",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Class Name"),
        ),
        migrations.AlterField(
            model_name="classschedule",
            name="class_obj",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="form.class",
                verbose_name="Class",
            ),
        ),
        migrations.AlterField(
            model_name="classschedule",
            name="day",
            field=models.CharField(
                choices=[
                    ("Sat", "Saturday"),
                    ("Sun", "Sunday"),
                    ("Mon", "Monday"),
                    ("Tue", "Tuesday"),
                    ("Wed", "Wednesday"),
                ],
                max_length=3,
                verbose_name="Day",
            ),
        ),
        migrations.AlterField(
            model_name="classschedule",
            name="is_split",
            field=models.BooleanField(default=False, verbose_name="Split Period"),
        ),
        migrations.AlterField(
            model_name="classschedule",
            name="schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_schedules",
                to="form.schedule",
                verbose_name="Schedule",
            ),
        ),
        migrations.AlterField(
            model_name="classschedule",
            name="split_part",
            field=models.PositiveIntegerField(default=0, verbose_name="Split Part"),
        ),
        migrations.AlterField(
            model_name="classschedule",
            name="subject",
            field=models.CharField(default="", max_length=100, verbose_name="Subject"),
        ),
        migrations.AlterField(
            model_name="classschedule",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_schedules",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Teacher",
            ),
        ),
        migrations.AlterField(
            model_name="classschedule",
            name="unit",
            field=models.CharField(default="", max_length=10, verbose_name="Unit"),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="end_time",
            field=models.TimeField(blank=True, null=True, verbose_name="End Time"),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="start_time",
            field=models.TimeField(blank=True, null=True, verbose_name="Start Time"),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="zeng",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "Period 1"),
                    (2, "Period 2"),
                    (3, "Period 3"),
                    (4, "Period 4"),
                    (5, "All Periods"),
                ],
                verbose_name="Period",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="class_obj",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="form.class",
                verbose_name="Class",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="father_name",
            field=models.CharField(max_length=50, verbose_name="Father's Name"),
        ),
        migrations.AlterField(
            model_name="student",
            name="first_name",
            field=models.CharField(max_length=50, verbose_name="First Name"),
        ),
        migrations.AlterField(
            model_name="student",
            name="last_name",
            field=models.CharField(max_length=50, verbose_name="Last Name"),
        ),
        migrations.AlterField(
            model_name="student",
            name="row_number",
            field=models.PositiveIntegerField(verbose_name="Row Number"),
        ),
    ]
