# Generated by Django 5.1.7 on 2026-01-06 11:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GradeLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="نام پایه")),
            ],
            options={
                "verbose_name": "پایه تحصیلی",
                "verbose_name_plural": "پایه\u200cهای تحصیلی",
            },
        ),
        migrations.CreateModel(
            name="Major",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام رشته")),
            ],
            options={
                "verbose_name": "رشته",
                "verbose_name_plural": "رشته\u200cها",
            },
        ),
        migrations.AlterModelOptions(
            name="attendance",
            options={"verbose_name": "Attendance", "verbose_name_plural": "حضور غیاب"},
        ),
        migrations.AlterModelOptions(
            name="class",
            options={"verbose_name": "Class", "verbose_name_plural": "کلاس ها"},
        ),
        migrations.AlterModelOptions(
            name="classschedule",
            options={
                "verbose_name": "Class Schedule",
                "verbose_name_plural": "کلاس های فعال",
            },
        ),
        migrations.AlterModelOptions(
            name="schedule",
            options={"verbose_name": "Schedule", "verbose_name_plural": "زنگ"},
        ),
        migrations.AlterModelOptions(
            name="student",
            options={"verbose_name": "Student", "verbose_name_plural": "دانش آموز"},
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان آزمون")),
                (
                    "duration",
                    models.PositiveIntegerField(
                        help_text="زمان آزمون به دقیقه", verbose_name="مدت زمان (دقیقه)"
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="زمان شروع"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "class_obj",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exams",
                        to="form.class",
                        verbose_name="کلاس",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exams",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="معلم",
                    ),
                ),
                (
                    "grade_level",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="form.gradelevel",
                        verbose_name="پایه تحصیلی",
                    ),
                ),
                (
                    "major",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="form.major",
                        verbose_name="رشته",
                    ),
                ),
            ],
            options={
                "verbose_name": "آزمون",
                "verbose_name_plural": "آزمون\u200cها",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="متن سوال")),
                ("option1", models.CharField(max_length=200, verbose_name="گزینه ۱")),
                ("option2", models.CharField(max_length=200, verbose_name="گزینه ۲")),
                ("option3", models.CharField(max_length=200, verbose_name="گزینه ۳")),
                ("option4", models.CharField(max_length=200, verbose_name="گزینه ۴")),
                (
                    "correct_option",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "گزینه ۱"),
                            (2, "گزینه ۲"),
                            (3, "گزینه ۳"),
                            (4, "گزینه ۴"),
                        ],
                        verbose_name="گزینه درست",
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="form.exam",
                        verbose_name="آزمون",
                    ),
                ),
            ],
            options={
                "verbose_name": "سوال",
                "verbose_name_plural": "سوالات",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="StudentAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "selected_option",
                    models.PositiveIntegerField(verbose_name="گزینه انتخاب\u200cشده"),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ارسال"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="form.question",
                        verbose_name="سوال",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="form.student",
                        verbose_name="دانش\u200cآموز",
                    ),
                ),
            ],
            options={
                "verbose_name": "پاسخ دانش\u200cآموز",
                "verbose_name_plural": "پاسخ\u200cهای دانش\u200cآموزان",
            },
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField(default=0, verbose_name="نمره")),
                (
                    "calculated_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان محاسبه"),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to="form.exam",
                        verbose_name="آزمون",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to="form.student",
                        verbose_name="دانش\u200cآموز",
                    ),
                ),
            ],
            options={
                "verbose_name": "نمره",
                "verbose_name_plural": "نمرات",
                "unique_together": {("student", "exam")},
            },
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(
                fields=["teacher", "class_obj"], name="form_exam_teacher_a69b32_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentanswer",
            index=models.Index(
                fields=["student", "question"], name="form_studen_student_5c84bf_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studentanswer",
            unique_together={("student", "question")},
        ),
    ]
