# Generated by Django 5.2.6 on 2025-10-18 08:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0002_alter_attendance_options_alter_class_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["student", "date"], name="form_attend_student_6d0a4d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="class",
            index=models.Index(fields=["name"], name="form_class_name_029e38_idx"),
        ),
        migrations.AddIndex(
            model_name="classschedule",
            index=models.Index(
                fields=["class_obj", "schedule", "day"],
                name="form_classs_class_o_8aa1e2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="schedule",
            index=models.Index(fields=["zeng"], name="form_schedu_zeng_b6b0fb_idx"),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["first_name", "last_name"],
                name="form_studen_first_n_0d3183_idx",
            ),
        ),
    ]
