# Generated by Django 5.1.7 on 2026-01-06 17:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0002_gradelevel_major_alter_attendance_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EntryPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.TextField(blank=True, null=True, verbose_name="دلیل تأخیر"),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="تاریخ"
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        default=django.utils.timezone.now, verbose_name="ساعت"
                    ),
                ),
                (
                    "approved",
                    models.BooleanField(
                        default=False, verbose_name="تأیید شده توسط معلم"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_permissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ایجاد شده توسط",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entry_permissions",
                        to="form.student",
                        verbose_name="دانش\u200cآموز",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entry_permissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="معلم",
                    ),
                ),
            ],
            options={
                "verbose_name": "اجازه ورود",
                "verbose_name_plural": "اجازه\u200cهای ورود",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(verbose_name="پیام")),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="خوانده شده"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="گیرنده",
                    ),
                ),
                (
                    "related_permission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="form.entrypermission",
                        verbose_name="مرتبط با اجازه ورود",
                    ),
                ),
            ],
            options={
                "verbose_name": "نوتیفیکیشن",
                "verbose_name_plural": "نوتیفیکیشن\u200cها",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="entrypermission",
            index=models.Index(
                fields=["student", "date"], name="form_entryp_student_acde5a_idx"
            ),
        ),
    ]
