# Generated by Django 5.1.7 on 2026-01-08 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0003_entrypermission_notification_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="grade_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="form.gradelevel",
                verbose_name="پایه تحصیلی",
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="major",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="form.major",
                verbose_name="رشته",
            ),
        ),
        migrations.CreateModel(
            name="StudentRegistrationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50, verbose_name="نام")),
                (
                    "last_name",
                    models.CharField(max_length=50, verbose_name="نام خانوادگی"),
                ),
                (
                    "nickname",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="نام مستعار"
                    ),
                ),
                (
                    "father_name",
                    models.CharField(max_length=50, verbose_name="نام پدر"),
                ),
                ("birth_day", models.PositiveIntegerField(verbose_name="روز تولد")),
                ("birth_month", models.PositiveIntegerField(verbose_name="ماه تولد")),
                ("birth_year", models.PositiveIntegerField(verbose_name="سال تولد")),
                (
                    "national_code",
                    models.CharField(max_length=10, verbose_name="کد ملی"),
                ),
                (
                    "family_type",
                    models.TextField(blank=True, verbose_name="نوع خانواده"),
                ),
                (
                    "children_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="تعداد فرزندان"
                    ),
                ),
                (
                    "boys_count",
                    models.PositiveIntegerField(default=0, verbose_name="تعداد پسر"),
                ),
                (
                    "girls_count",
                    models.PositiveIntegerField(default=0, verbose_name="تعداد دختر"),
                ),
                (
                    "child_order",
                    models.PositiveIntegerField(default=1, verbose_name="ترتیب فرزند"),
                ),
                (
                    "family_info",
                    models.JSONField(default=dict, verbose_name="اطلاعات خانواده"),
                ),
                ("province", models.CharField(max_length=100, verbose_name="استان")),
                ("county", models.CharField(max_length=100, verbose_name="شهرستان")),
                ("city", models.CharField(max_length=100, verbose_name="شهر")),
                (
                    "postal_code",
                    models.CharField(max_length=10, verbose_name="کد پستی"),
                ),
                (
                    "home_phone",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="شماره منزل"
                    ),
                ),
                (
                    "father_education",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="تحصیلات پدر"
                    ),
                ),
                (
                    "mother_education",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="تحصیلات مادر"
                    ),
                ),
                (
                    "father_phone",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="شماره پدر"
                    ),
                ),
                (
                    "mother_phone",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="شماره مادر"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="آدرس")),
                (
                    "interests_morning",
                    models.TextField(
                        blank=True, verbose_name="علاقه\u200cمندی صبحگاهی"
                    ),
                ),
                (
                    "interests_prayer",
                    models.TextField(blank=True, verbose_name="علاقه\u200cمندی نماز"),
                ),
                (
                    "interests_art",
                    models.TextField(blank=True, verbose_name="علاقه\u200cمندی هنری"),
                ),
                (
                    "competitions_quran",
                    models.TextField(blank=True, verbose_name="مسابقات قرآن"),
                ),
                (
                    "competitions_sport",
                    models.TextField(blank=True, verbose_name="مسابقات ورزشی"),
                ),
                (
                    "achievements",
                    models.JSONField(default=list, verbose_name="عناوین کسب شده"),
                ),
                (
                    "other_skills",
                    models.TextField(blank=True, verbose_name="سایر مهارت\u200cها"),
                ),
                (
                    "diseases",
                    models.TextField(blank=True, verbose_name="بیماری\u200cهای خاص"),
                ),
                (
                    "report_card_image",
                    models.ImageField(
                        upload_to="report_cards/", verbose_name="عکس کارنامه"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("P", "Pending"),
                            ("A", "Approved"),
                            ("R", "Rejected"),
                        ],
                        default="P",
                        max_length=1,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="یادداشت ادمین"
                    ),
                ),
                (
                    "class_assigned",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="form.class",
                        verbose_name="کلاس割り当て شده",
                    ),
                ),
                (
                    "grade_level",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="form.gradelevel",
                        verbose_name="پایه تحصیلی",
                    ),
                ),
                (
                    "major",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="form.major",
                        verbose_name="رشته",
                    ),
                ),
            ],
            options={
                "verbose_name": "درخواست ثبت نام دانش\u200cآموز",
                "verbose_name_plural": "درخواست\u200cهای ثبت نام",
            },
        ),
    ]
