# Generated by Django 5.1.7 on 2026-01-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0004_class_grade_level_class_major_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentregistrationrequest",
            name="achievements",
            field=models.TextField(blank=True, verbose_name="عناوین کسب شده"),
        ),
        migrations.AlterField(
            model_name="studentregistrationrequest",
            name="family_info",
            field=models.TextField(blank=True, verbose_name="اطلاعات خانواده"),
        ),
    ]
