# Generated by Django 5.1.7 on 2026-01-08 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0005_alter_studentregistrationrequest_achievements_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendance",
            options={"verbose_name": "Attendance", "verbose_name_plural": "حضور"},
        ),
        migrations.AlterModelOptions(
            name="class",
            options={"verbose_name": "Class", "verbose_name_plural": "کلاس"},
        ),
        migrations.AlterModelOptions(
            name="exam",
            options={"verbose_name": "آزمون", "verbose_name_plural": "آزمون"},
        ),
        migrations.AlterModelOptions(
            name="gradelevel",
            options={"verbose_name": "پایه تحصیلی", "verbose_name_plural": "پایه"},
        ),
    ]
