# Generated by Django 5.1.7 on 2026-01-06 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name": "User", "verbose_name_plural": "کاربران"},
        ),
    ]
