# Generated by Django 5.2.6 on 2025-10-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان صفحه")),
                (
                    "subtitle",
                    models.CharField(max_length=500, verbose_name="زیرعنوان صفحه"),
                ),
                ("description", models.TextField(verbose_name="توضیحات")),
                (
                    "stat_store_icon",
                    models.CharField(
                        default="store", max_length=100, verbose_name="آیکون فروشگاه"
                    ),
                ),
                (
                    "stat_store_number",
                    models.CharField(
                        default="۱,۲۵۰+", max_length=50, verbose_name="تعداد فروشگاه"
                    ),
                ),
                (
                    "stat_store_label",
                    models.CharField(
                        default="فروشگاه فعال",
                        max_length=100,
                        verbose_name="برچسب فروشگاه",
                    ),
                ),
                (
                    "stat_users_icon",
                    models.CharField(
                        default="users", max_length=100, verbose_name="آیکون کاربران"
                    ),
                ),
                (
                    "stat_users_number",
                    models.CharField(
                        default="۵۰,۰۰۰+", max_length=50, verbose_name="تعداد کاربران"
                    ),
                ),
                (
                    "stat_users_label",
                    models.CharField(
                        default="کاربر ثبت\u200cنام شده",
                        max_length=100,
                        verbose_name="برچسب کاربران",
                    ),
                ),
                (
                    "stat_rating_icon",
                    models.CharField(
                        default="star", max_length=100, verbose_name="آیکون رضایت"
                    ),
                ),
                (
                    "stat_rating_number",
                    models.CharField(
                        default="۴.۸/۵", max_length=50, verbose_name="امتیاز رضایت"
                    ),
                ),
                (
                    "stat_rating_label",
                    models.CharField(
                        default="رضایت کاربران",
                        max_length=100,
                        verbose_name="برچسب رضایت",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ به\u200cروزرسانی"
                    ),
                ),
            ],
            options={
                "verbose_name": "صفحه درباره ما",
                "verbose_name_plural": "About Us Pages",
            },
        ),
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(default="با ما در ارتباط باشید", max_length=100),
                ),
                (
                    "description",
                    models.TextField(
                        default="تیم پشتیبانی ما آماده پاسخگویی به سوالات و دریافت پیشنهادات شما می\u200cباشد."
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        default="تهران، خیابان ولیعصر، پلاک ۱۲۳۴، طبقه ۵",
                        max_length=255,
                    ),
                ),
                ("phone", models.CharField(default="۰۲۱-۱۲۳۴۵۶۷۸", max_length=20)),
                (
                    "email",
                    models.EmailField(default="info@example.com", max_length=254),
                ),
                (
                    "work_hours",
                    models.CharField(
                        default="شنبه تا چهارشنبه: ۸:۰۰ - ۱۷:۰۰ | پنجشنبه: ۸:۰۰ - ۱۴:۰۰",
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("subject", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="نام")),
                ("role", models.CharField(max_length=200, verbose_name="نقش")),
                ("bio", models.TextField(verbose_name="بیوگرافی")),
                (
                    "image",
                    models.ImageField(upload_to="team_images/", verbose_name="تصویر"),
                ),
                ("linkedin_url", models.URLField(blank=True, verbose_name="لینکدین")),
                ("twitter_url", models.URLField(blank=True, verbose_name="توییتر")),
                (
                    "github_url",
                    models.URLField(blank=True, verbose_name="گیت\u200cهاب"),
                ),
                (
                    "instagram_url",
                    models.URLField(blank=True, verbose_name="اینستاگرام"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ به\u200cروزرسانی"
                    ),
                ),
            ],
            options={
                "verbose_name": "عضو تیم",
                "verbose_name_plural": "Team members",
            },
        ),
    ]
