# Generated by Django 5.1.7 on 2026-01-05 19:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="Slug"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="EducationalResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                ("description", models.TextField(verbose_name="توضیحات")),
                (
                    "grade",
                    models.IntegerField(
                        choices=[
                            (10, "پایه دهم"),
                            (11, "پایه یازدهم"),
                            (12, "پایه دوازدهم"),
                        ],
                        verbose_name="پایه تحصیلی",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="resources/",
                        verbose_name="فایل",
                    ),
                ),
                (
                    "video_url",
                    models.URLField(blank=True, null=True, verbose_name="لینک ویدیو"),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="thumbnails/",
                        verbose_name="تصویر شاخص",
                    ),
                ),
                (
                    "file_size",
                    models.FloatField(
                        blank=True, null=True, verbose_name="حجم فایل (مگابایت)"
                    ),
                ),
                (
                    "duration",
                    models.DurationField(
                        blank=True, null=True, verbose_name="مدت زمان ویدیو"
                    ),
                ),
                (
                    "download_count",
                    models.IntegerField(default=0, verbose_name="تعداد دانلود"),
                ),
                (
                    "view_count",
                    models.IntegerField(default=0, verbose_name="تعداد بازدید"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاریخ ایجاد"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
            ],
            options={
                "verbose_name": "منبع آموزشی",
                "verbose_name_plural": "Educational resources",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Major",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="عنوان رشته")),
                ("description", models.TextField(verbose_name="توضیحات")),
                (
                    "image",
                    models.ImageField(upload_to="majors/", verbose_name="تصویر رشته"),
                ),
                (
                    "icon",
                    models.CharField(
                        help_text="یک ایموجی مثل 📱 یا 💻 وارد کنید",
                        max_length=10,
                        verbose_name="آیکون (ایموجی)",
                    ),
                ),
                ("subtitle", models.CharField(max_length=200, verbose_name="زیرعنوان")),
                ("introduction", models.TextField(verbose_name="معرفی رشته")),
            ],
            options={
                "verbose_name": "رشته تحصیلی",
                "verbose_name_plural": "Fields of study",
            },
        ),
        migrations.CreateModel(
            name="ResourceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نوع منبع")),
                (
                    "icon",
                    models.CharField(
                        help_text="نام کلاس FontAwesome",
                        max_length=50,
                        verbose_name="آیکون",
                    ),
                ),
            ],
            options={
                "verbose_name": "نوع منبع",
                "verbose_name_plural": "انواع منابع",
            },
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                (
                    "slug",
                    models.SlugField(max_length=200, unique=True, verbose_name="Slug"),
                ),
                ("content", models.TextField(verbose_name="Content")),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Address"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="City"
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="District"
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="Is Approved"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blogs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blogs",
                        to="index.category",
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog",
                "verbose_name_plural": "Blogs",
            },
        ),
        migrations.CreateModel(
            name="BlogImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="blog_images/", verbose_name="Image"),
                ),
                (
                    "blog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="index.blog",
                        verbose_name="Blog",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog Image",
                "verbose_name_plural": "Blog Images",
            },
        ),
        migrations.CreateModel(
            name="DownloadLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "downloaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان دانلود"),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="آدرس IP")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="index.educationalresource",
                        verbose_name="منبع",
                    ),
                ),
            ],
            options={
                "verbose_name": "لاگ دانلود",
                "verbose_name_plural": "لاگ\u200cهای دانلود",
            },
        ),
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=200, verbose_name="ویژگی")),
                (
                    "major",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="index.major",
                        verbose_name="رشته",
                    ),
                ),
            ],
            options={
                "verbose_name": "ویژگی",
                "verbose_name_plural": "ویژگی\u200cها",
            },
        ),
        migrations.AddField(
            model_name="educationalresource",
            name="major",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="index.major",
                verbose_name="رشته تحصیلی",
            ),
        ),
        migrations.CreateModel(
            name="Career",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=200, verbose_name="شغل")),
                (
                    "major",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="careers",
                        to="index.major",
                        verbose_name="رشته",
                    ),
                ),
            ],
            options={
                "verbose_name": "شغل",
                "verbose_name_plural": "مشاغل",
            },
        ),
        migrations.CreateModel(
            name="Requirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=200, verbose_name="شرط ورود")),
                (
                    "major",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirements",
                        to="index.major",
                        verbose_name="رشته",
                    ),
                ),
            ],
            options={
                "verbose_name": "شرط ورود",
                "verbose_name_plural": "شرایط ورود",
            },
        ),
        migrations.AddField(
            model_name="educationalresource",
            name="resource_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="index.resourcetype",
                verbose_name="نوع منبع",
            ),
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=200, verbose_name="مهارت")),
                (
                    "major",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="index.major",
                        verbose_name="رشته",
                    ),
                ),
            ],
            options={
                "verbose_name": "مهارت",
                "verbose_name_plural": "مهارت\u200cها",
            },
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=200, verbose_name="نام کامل"),
                ),
                ("specialty", models.CharField(max_length=100, verbose_name="تخصص")),
                ("bio", models.TextField(blank=True, verbose_name="بیوگرافی")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="teachers/",
                        verbose_name="تصویر",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "استاد",
                "verbose_name_plural": "اساتید",
            },
        ),
        migrations.AddField(
            model_name="educationalresource",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="index.teacher",
                verbose_name="استاد",
            ),
        ),
        migrations.CreateModel(
            name="ViewLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "viewed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان مشاهده"),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="آدرس IP")),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="index.educationalresource",
                        verbose_name="منبع",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "لاگ مشاهده",
                "verbose_name_plural": "لاگ\u200cهای مشاهده",
            },
        ),
        migrations.CreateModel(
            name="Work",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="works/", verbose_name="تصویر نمونه\u200cکار"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="عنوان نمونه\u200cکار"
                    ),
                ),
                (
                    "major",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="works",
                        to="index.major",
                        verbose_name="رشته",
                    ),
                ),
            ],
            options={
                "verbose_name": "نمونه\u200cکار",
                "verbose_name_plural": "نمونه\u200cکارها",
            },
        ),
        migrations.CreateModel(
            name="BlogComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.FloatField(default=0.0, verbose_name="Rating")),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Comment"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "blog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="index.blog",
                        verbose_name="Blog",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog Comment",
                "verbose_name_plural": "Blog Comments",
                "unique_together": {("blog", "user")},
            },
        ),
    ]
