# Generated by Django 5.1.7 on 2026-01-06 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={"verbose_name": "Blog", "verbose_name_plural": "وبلاگ ها"},
        ),
        migrations.AlterModelOptions(
            name="blogcomment",
            options={"verbose_name": "Blog Comment", "verbose_name_plural": "کامنت ها"},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "دسته بندی"},
        ),
        migrations.AlterModelOptions(
            name="educationalresource",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "منبع آموزشی",
                "verbose_name_plural": "فایل",
            },
        ),
        migrations.AlterModelOptions(
            name="major",
            options={"verbose_name": "رشته تحصیلی", "verbose_name_plural": "رشته ها"},
        ),
    ]
