# Generated by Django 5.2.6 on 2025-10-16 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Major",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="عنوان رشته")),
                ("description", models.TextField(verbose_name="توضیحات")),
                (
                    "image",
                    models.ImageField(upload_to="majors/", verbose_name="تصویر رشته"),
                ),
                (
                    "icon",
                    models.CharField(
                        help_text="یک ایموجی مثل 📱 یا 💻 وارد کنید",
                        max_length=10,
                        verbose_name="آیکون (ایموجی)",
                    ),
                ),
                ("subtitle", models.CharField(max_length=200, verbose_name="زیرعنوان")),
                ("introduction", models.TextField(verbose_name="معرفی رشته")),
            ],
            options={
                "verbose_name": "رشته",
                "verbose_name_plural": "رشته\u200cها",
            },
        ),
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=200, verbose_name="ویژگی")),
                (
                    "major",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="index.major",
                        verbose_name="رشته",
                    ),
                ),
            ],
            options={
                "verbose_name": "ویژگی",
                "verbose_name_plural": "ویژگی\u200cها",
            },
        ),
        migrations.CreateModel(
            name="Career",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=200, verbose_name="شغل")),
                (
                    "major",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="careers",
                        to="index.major",
                        verbose_name="رشته",
                    ),
                ),
            ],
            options={
                "verbose_name": "شغل",
                "verbose_name_plural": "مشاغل",
            },
        ),
        migrations.CreateModel(
            name="Requirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=200, verbose_name="شرط ورود")),
                (
                    "major",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirements",
                        to="index.major",
                        verbose_name="رشته",
                    ),
                ),
            ],
            options={
                "verbose_name": "شرط ورود",
                "verbose_name_plural": "شرایط ورود",
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=200, verbose_name="مهارت")),
                (
                    "major",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="index.major",
                        verbose_name="رشته",
                    ),
                ),
            ],
            options={
                "verbose_name": "مهارت",
                "verbose_name_plural": "مهارت\u200cها",
            },
        ),
        migrations.CreateModel(
            name="Work",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="works/", verbose_name="تصویر نمونه\u200cکار"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="عنوان نمونه\u200cکار"
                    ),
                ),
                (
                    "major",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="works",
                        to="index.major",
                        verbose_name="رشته",
                    ),
                ),
            ],
            options={
                "verbose_name": "نمونه\u200cکار",
                "verbose_name_plural": "نمونه\u200cکارها",
            },
        ),
    ]
