# Generated by Django 5.2.6 on 2025-10-16 18:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0002_major_feature_career_requirement_skill_work"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نوع منبع")),
                (
                    "icon",
                    models.CharField(
                        help_text="نام کلاس FontAwesome",
                        max_length=50,
                        verbose_name="آیکون",
                    ),
                ),
            ],
            options={
                "verbose_name": "نوع منبع",
                "verbose_name_plural": "انواع منابع",
            },
        ),
        migrations.AlterModelOptions(
            name="major",
            options={
                "verbose_name": "رشته تحصیلی",
                "verbose_name_plural": "رشته\u200cهای تحصیلی",
            },
        ),
        migrations.CreateModel(
            name="EducationalResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                ("description", models.TextField(verbose_name="توضیحات")),
                (
                    "grade",
                    models.IntegerField(
                        choices=[
                            (10, "پایه دهم"),
                            (11, "پایه یازدهم"),
                            (12, "پایه دوازدهم"),
                        ],
                        verbose_name="پایه تحصیلی",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="resources/",
                        verbose_name="فایل",
                    ),
                ),
                (
                    "video_url",
                    models.URLField(blank=True, null=True, verbose_name="لینک ویدیو"),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="thumbnails/",
                        verbose_name="تصویر شاخص",
                    ),
                ),
                (
                    "file_size",
                    models.FloatField(
                        blank=True, null=True, verbose_name="حجم فایل (مگابایت)"
                    ),
                ),
                (
                    "duration",
                    models.DurationField(
                        blank=True, null=True, verbose_name="مدت زمان ویدیو"
                    ),
                ),
                (
                    "download_count",
                    models.IntegerField(default=0, verbose_name="تعداد دانلود"),
                ),
                (
                    "view_count",
                    models.IntegerField(default=0, verbose_name="تعداد بازدید"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاریخ ایجاد"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "major",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="index.major",
                        verbose_name="رشته تحصیلی",
                    ),
                ),
                (
                    "resource_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="index.resourcetype",
                        verbose_name="نوع منبع",
                    ),
                ),
            ],
            options={
                "verbose_name": "منبع آموزشی",
                "verbose_name_plural": "منابع آموزشی",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DownloadLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "downloaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان دانلود"),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="آدرس IP")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="index.educationalresource",
                        verbose_name="منبع",
                    ),
                ),
            ],
            options={
                "verbose_name": "لاگ دانلود",
                "verbose_name_plural": "لاگ\u200cهای دانلود",
            },
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=200, verbose_name="نام کامل"),
                ),
                ("specialty", models.CharField(max_length=100, verbose_name="تخصص")),
                ("bio", models.TextField(blank=True, verbose_name="بیوگرافی")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="teachers/",
                        verbose_name="تصویر",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "استاد",
                "verbose_name_plural": "اساتید",
            },
        ),
        migrations.AddField(
            model_name="educationalresource",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="index.teacher",
                verbose_name="استاد",
            ),
        ),
        migrations.CreateModel(
            name="ViewLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "viewed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان مشاهده"),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="آدرس IP")),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="index.educationalresource",
                        verbose_name="منبع",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "لاگ مشاهده",
                "verbose_name_plural": "لاگ\u200cهای مشاهده",
            },
        ),
    ]
