# Generated by Django 5.2.6 on 2025-10-18 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0003_resourcetype_alter_major_options_educationalresource_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="educationalresource",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "منبع آموزشی",
                "verbose_name_plural": "Educational resources",
            },
        ),
        migrations.AlterModelOptions(
            name="major",
            options={
                "verbose_name": "رشته تحصیلی",
                "verbose_name_plural": "Fields of study",
            },
        ),
    ]
